# services:
#   db:
#     image: postgres:14
#     restart: always
#     environment: 
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     ports:
#       - '5432:5432'
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   server:
#     image: webauthnserver
#     ports:
#       - '3000:3000'
#     depends_on:
#       dbsetup:
#         condition: service_completed_successfully

services:
  db:
    image: postgres:14
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # dbsetup:
  #   image: postgres:14
  #   restart: "no"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   volumes:
  #     - ./dbsetup.sh:/dbsetup.sh
  #   command: sh -c "./dbsetup.sh"

  server:
    image: webauthnserver
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      serversetup:
        condition: service_completed_successfully

  serversetup:
    image: webauthnserver
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    command: npx prisma migrate deploy
